# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

deck1 = Deck.create(name: "Initial K")
deck2 = Deck.create(name: "Initial SH")

card1 = Card.create(word: "cat")
card2 = Card.create(word: "car")
card3 = Card.create(word: "cow")
card4 = Card.create(word: "shed")
card5 = Card.create(word: "shears")
card6 = Card.create(word: "shaggy")
card7 = Card.create(word: "shoes")
card8 = Card.create(word: "sheep")
card9 = Card.create(word: "ship")
card10 = Card.create(word: "shelves")
card11 = Card.create(word: "shade")
card12 = Card.create(word: "shovel")
card13 = Card.create(word: "shot")
card14 = Card.create(word: "shorts")
card15 = Card.create(word: "shirt")
card16 = Card.create(word: "share")
card17 = Card.create(word: "chef")
card18 = Card.create(word: "shake")
card19 = Card.create(word: "shapes")
card20 = Card.create(word: "shave")
card21 = Card.create(word: "sheets")
card22 = Card.create(word: "shiny")
card23 = Card.create(word: "shampoo")
card24 = Card.create(word: "shoulders")
card25 = Card.create(word: "shower")
card26 = Card.create(word: "sharpener")

CardDeck.create(card: card1, deck: deck1)
CardDeck.create(card: card2, deck: deck1)
CardDeck.create(card: card3, deck: deck1)
CardDeck.create(card: card4, deck: deck2)
CardDeck.create(card: card5, deck: deck2)
CardDeck.create(card: card6, deck: deck2)
CardDeck.create(card: card7, deck: deck2)
CardDeck.create(card: card8, deck: deck2)
CardDeck.create(card: card9, deck: deck2)
CardDeck.create(card: card10, deck: deck2)
CardDeck.create(card: card11, deck: deck2)
CardDeck.create(card: card12, deck: deck2)
CardDeck.create(card: card13, deck: deck2)
CardDeck.create(card: card14, deck: deck2)
CardDeck.create(card: card15, deck: deck2)
CardDeck.create(card: card16, deck: deck2)
CardDeck.create(card: card17, deck: deck2)
CardDeck.create(card: card18, deck: deck2)
CardDeck.create(card: card19, deck: deck2)
CardDeck.create(card: card20, deck: deck2)
CardDeck.create(card: card21, deck: deck2)
CardDeck.create(card: card22, deck: deck2)
CardDeck.create(card: card23, deck: deck2)
CardDeck.create(card: card24, deck: deck2)
CardDeck.create(card: card25, deck: deck2)
CardDeck.create(card: card26, deck: deck2)