# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

deck1 = Deck.create(name: "Initial /k/")
deck2 = Deck.create(name: "Initial /sh/")
deck3 = Deck.create(name: "Initial /s/ Blends")
deck4 = Deck.create(name: "Final /st/")
deck5 = Deck.create(name: "Final /b/")

card1 = Card.create(word: "cat")
card2 = Card.create(word: "car")
card3 = Card.create(word: "cow")
card72 = Card.create(word: "cage")
card73 = Card.create(word: "carrot")
card74 = Card.create(word: "candy")
card75 = Card.create(word: "car")
card76 = Card.create(word: "corn")
card77 = Card.create(word: "coat")
card78 = Card.create(word: "comb")

card4 = Card.create(word: "shed")
card5 = Card.create(word: "shears")
card6 = Card.create(word: "shaggy")
card7 = Card.create(word: "shoes")
card8 = Card.create(word: "sheep")
card9 = Card.create(word: "ship")
card10 = Card.create(word: "shelves")
card11 = Card.create(word: "shade")
card12 = Card.create(word: "shovel")
card13 = Card.create(word: "shot")
card14 = Card.create(word: "shorts")
card15 = Card.create(word: "shirt")
card16 = Card.create(word: "share")
card17 = Card.create(word: "chef")
card18 = Card.create(word: "shake")
card19 = Card.create(word: "shapes")
card20 = Card.create(word: "shave")
card21 = Card.create(word: "sheets")
card22 = Card.create(word: "shiny")
card23 = Card.create(word: "shampoo")
card24 = Card.create(word: "shoulders")
card25 = Card.create(word: "shower")
card26 = Card.create(word: "sharpener")

card27 = Card.create(word: "sled")
card28 = Card.create(word: "slip")
card29 = Card.create(word: "slot")
card30 = Card.create(word: "slate")
card31 = Card.create(word: "slide")
card32 = Card.create(word: "slow")
card33 = Card.create(word: "smock")
card34 = Card.create(word: "smoke")
card35 = Card.create(word: "small")
card36 = Card.create(word: "smell")
card37 = Card.create(word: "smile")
card38 = Card.create(word: "smooch")
card39 = Card.create(word: "snap")
card40 = Card.create(word: "snip")
card42 = Card.create(word: "snot")
card43 = Card.create(word: "spin")
card44 = Card.create(word: "spoon")
card45 = Card.create(word: "steam")
card46 = Card.create(word: "stain")
card47 = Card.create(word: "spade")
card48 = Card.create(word: "snout")

card49 = Card.create(word: "best")
card50 = Card.create(word: "cast")
card51 = Card.create(word: "fast")
card52 = Card.create(word: "fist")
card53 = Card.create(word: "last")
card54 = Card.create(word: "lost")
card55 = Card.create(word: "list")
card56 = Card.create(word: "most")
card57 = Card.create(word: "nest")
card58 = Card.create(word: "rest")
card59 = Card.create(word: "test")
card60 = Card.create(word: "chest")

card61 = Card.create(word: "bib")
card62 = Card.create(word: "sub")
card63 = Card.create(word: "crab")
card64 = Card.create(word: "tub")
card65 = Card.create(word: "crib")
card66 = Card.create(word: "rub")
card67 = Card.create(word: "robe")
card68 = Card.create(word: "tube")
card69 = Card.create(word: "web")
card70 = Card.create(word: "globe")
card71 = Card.create(word: "cube")

CardDeck.create(card: card1, deck: deck1)
CardDeck.create(card: card2, deck: deck1)
CardDeck.create(card: card3, deck: deck1)
CardDeck.create(card: card72, deck: deck1)
CardDeck.create(card: card73, deck: deck1)
CardDeck.create(card: card74, deck: deck1)
CardDeck.create(card: card75, deck: deck1)
CardDeck.create(card: card76, deck: deck1)
CardDeck.create(card: card77, deck: deck1)
CardDeck.create(card: card78, deck: deck1)

CardDeck.create(card: card4, deck: deck2)
CardDeck.create(card: card5, deck: deck2)
CardDeck.create(card: card6, deck: deck2)
CardDeck.create(card: card7, deck: deck2)
CardDeck.create(card: card8, deck: deck2)
CardDeck.create(card: card9, deck: deck2)
CardDeck.create(card: card10, deck: deck2)
CardDeck.create(card: card11, deck: deck2)
CardDeck.create(card: card12, deck: deck2)
CardDeck.create(card: card13, deck: deck2)
CardDeck.create(card: card14, deck: deck2)
CardDeck.create(card: card15, deck: deck2)
CardDeck.create(card: card16, deck: deck2)
CardDeck.create(card: card17, deck: deck2)
CardDeck.create(card: card18, deck: deck2)
CardDeck.create(card: card19, deck: deck2)
CardDeck.create(card: card20, deck: deck2)
CardDeck.create(card: card21, deck: deck2)
CardDeck.create(card: card22, deck: deck2)
CardDeck.create(card: card23, deck: deck2)
CardDeck.create(card: card24, deck: deck2)
CardDeck.create(card: card25, deck: deck2)
CardDeck.create(card: card26, deck: deck2)

CardDeck.create(card: card27, deck: deck3)
CardDeck.create(card: card28, deck: deck3)
CardDeck.create(card: card29, deck: deck3)
CardDeck.create(card: card30, deck: deck3)
CardDeck.create(card: card31, deck: deck3)
CardDeck.create(card: card32, deck: deck3)
CardDeck.create(card: card33, deck: deck3)
CardDeck.create(card: card34, deck: deck3)
CardDeck.create(card: card35, deck: deck3)
CardDeck.create(card: card36, deck: deck3)
CardDeck.create(card: card37, deck: deck3)
CardDeck.create(card: card38, deck: deck3)
CardDeck.create(card: card39, deck: deck3)
CardDeck.create(card: card40, deck: deck3)
CardDeck.create(card: card42, deck: deck3)
CardDeck.create(card: card43, deck: deck3)
CardDeck.create(card: card44, deck: deck3)
CardDeck.create(card: card45, deck: deck3)
CardDeck.create(card: card46, deck: deck3)
CardDeck.create(card: card47, deck: deck3)
CardDeck.create(card: card48, deck: deck3)

CardDeck.create(card: card49, deck: deck4)
CardDeck.create(card: card50, deck: deck4)
CardDeck.create(card: card51, deck: deck4)
CardDeck.create(card: card52, deck: deck4)
CardDeck.create(card: card53, deck: deck4)
CardDeck.create(card: card54, deck: deck4)
CardDeck.create(card: card55, deck: deck4)
CardDeck.create(card: card56, deck: deck4)
CardDeck.create(card: card57, deck: deck4)
CardDeck.create(card: card58, deck: deck4)
CardDeck.create(card: card59, deck: deck4)
CardDeck.create(card: card60, deck: deck4)

CardDeck.create(card: card61, deck: deck5)
CardDeck.create(card: card62, deck: deck5)
CardDeck.create(card: card63, deck: deck5)
CardDeck.create(card: card64, deck: deck5)
CardDeck.create(card: card65, deck: deck5)
CardDeck.create(card: card66, deck: deck5)
CardDeck.create(card: card67, deck: deck5)
CardDeck.create(card: card68, deck: deck5)
CardDeck.create(card: card69, deck: deck5)
CardDeck.create(card: card70, deck: deck5)